version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 12321
      MYSQL_DATABASE: fxdeals
    ports:
      - "3307:3306"
  datawarehouse1:
    build: /DataWareHouse
    restart: on-failure
    container_name: datawarehouse1-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  datawarehouse2:
    build: /DataWareHouse
    restart: on-failure
    container_name: datawarehouse2-container
    ports:
      - "8081:8080"
    depends_on:
      - mysql
  eureka-server:
    build: /EurekaServer
    image: spring-cloud/eureka
    container_name: eureka-server
    ports:
      - "9090:9090"
  load-balancer:
    build: /LoadBalancer
    container_name: load-balancer
    ports:
      - "8085:8085"
  bloom-berg:
    build: /BloomBergAPI
    container_name: bloom-berg
    ports:
      - "8082:8082"
